spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5455/warehouse_db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: 12345
  mvc:
    hidden-method:
      filter:
        enabled: true
  flyway:
    locations: classpath:db/migration
    enabled: false